package com.pojo;
// Generated Feb 5, 2018 12:41:58 AM by Hibernate Tools 4.3.1

import com.dao.AdminTableDAO;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * AdminTable generated by hbm2java
 */
@ManagedBean(name = "admin")
public class AdminTable implements java.io.Serializable {

    private int did;
    private String aid;
    private String apass;
    private String dpass;
    private String dname;
    private String daddress;
    private String dmobile;
    private String dcategory;
    private String demail;
    private String time;

    public AdminTable() {
    }

    public AdminTable(int did) {
        this.did = did;
    }

    public AdminTable(int did, String aid, String apass, String dpass, String dname, String daddress, String dmobile, String dcategory, String demail, String time) {
        this.did = did;
        this.aid = aid;
        this.apass = apass;
        this.dpass = dpass;
        this.dname = dname;
        this.daddress = daddress;
        this.dmobile = dmobile;
        this.dcategory = dcategory;
        this.demail = demail;
        this.time = time;
    }

    public int getDid() {
        return this.did;
    }

    public void setDid(int did) {
        this.did = did;
    }

    public String getAid() {
        return this.aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public String getApass() {
        return this.apass;
    }

    public void setApass(String apass) {
        this.apass = apass;
    }

    public String getDpass() {
        return this.dpass;
    }

    public void setDpass(String dpass) {
        this.dpass = dpass;
    }

    public String getDname() {
        return this.dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    public String getDaddress() {
        return this.daddress;
    }

    public void setDaddress(String daddress) {
        this.daddress = daddress;
    }

    public String getDmobile() {
        return this.dmobile;
    }

    public void setDmobile(String dmobile) {
        this.dmobile = dmobile;
    }

    public String getDcategory() {
        return this.dcategory;
    }

    public void setDcategory(String dcategory) {
        this.dcategory = dcategory;
    }

    public String getDemail() {
        return this.demail;
    }

    public void setDemail(String demail) {
        this.demail = demail;
    }

    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public void doInsert() {
        AdminTableDAO ad = new AdminTableDAO();
        ad.doSave(this);
    }
    public void doUpdate() {
        AdminTableDAO ad = new AdminTableDAO();
        ad.doUp(this);
    }

    public String adminLog() {
        String ret = "fail";
        AdminTableDAO ad = new AdminTableDAO();
        if (ad.aAdmin(aid, apass) != null) {
            ret = "success";
        } else {
            ret = "fail";
        }
        return ret;
    }

    public String doctorLog() {
        String ret = "fail";
        AdminTableDAO ad = new AdminTableDAO();
        if (ad.aDoctor(did, dpass) != null) {
            ret = "success";
        } else {
            ret = "fail";
        }
        return ret;
    }

    private List<Integer> liId = new ArrayList<>();
    private List<AdminTable> showAllP = new ArrayList<>();

    public List<Integer> getLiId() {
        AdminTableDAO ad = new AdminTableDAO();
        liId = ad.shId();
        return liId;
    }

    public void setLiId(List<Integer> liId) {
        this.liId = liId;
    }

    public List<AdminTable> getShowAllP() {
        AdminTableDAO ad = new AdminTableDAO();
        showAllP = ad.showAll();
        return showAllP;
    }

    public void setShowAllP(List<AdminTable> showAll) {
        this.showAllP = showAll;
    }

    public void findaPatient() {
        AdminTableDAO ad = new AdminTableDAO();
        AdminTable p = ad.aDocReg(did);
        this.did = p.did;
        this.aid = p.aid;
        this.apass = p.apass;
        this.dpass = p.dpass;
        this.dname = p.dname;
        this.daddress = p.daddress;
        this.dmobile = p.dmobile;
        this.dcategory = p.dcategory;
        this.demail = p.demail;
        this.time = p.time;
    }

}
