package com.pojo;
// Generated Feb 5, 2018 12:41:58 AM by Hibernate Tools 4.3.1

import com.dao.PatientRegDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * PatientReg generated by hbm2java
 */
@ManagedBean(name = "patient")
public class PatientReg implements java.io.Serializable {

    private int id;
    private String password;
    private String name;
    private String address;
    private String mobileNo;
    private String email;
    private String gender;
    private String age;
    private Date bookDate;
    private String treatment;
    private String treatmentFor;
    private String feedback;

    public PatientReg() {
    }

    public PatientReg(int id) {
        this.id = id;
    }

    public PatientReg(int id, String password, String name, String address, String mobileNo, String email, String gender, String age, Date bookDate, String treatment, String treatmentFor, String feedback) {
        this.id = id;
        this.password = password;
        this.name = name;
        this.address = address;
        this.mobileNo = mobileNo;
        this.email = email;
        this.gender = gender;
        this.age = age;
        this.bookDate = bookDate;
        this.treatment = treatment;
        this.treatmentFor = treatmentFor;
        this.feedback = feedback;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobileNo() {
        return this.mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public Date getBookDate() {
        return this.bookDate;
    }

    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    public String getTreatment() {
        return this.treatment;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getTreatmentFor() {
        return this.treatmentFor;
    }

    public void setTreatmentFor(String treatmentFor) {
        this.treatmentFor = treatmentFor;
    }

    public String getFeedback() {
        return this.feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public void doInsert() {
        PatientRegDAO pd = new PatientRegDAO();
        pd.doSave(this);
    }

    public void doUpdate() {
        PatientRegDAO pd = new PatientRegDAO();
        pd.doUp(this);
    }

    public String doLogin() {
        String ret = "fail";
        PatientRegDAO pd = new PatientRegDAO();
        if (pd.aPatient(id, password) != null) {
            ret = "success";
        } else {

            ret = "fail";
        }
        return ret;
    }

    private List<Integer> liId = new ArrayList<>();
    private List<PatientReg> showAllP = new ArrayList<>();

    public List<Integer> getLiId() {
        PatientRegDAO da = new PatientRegDAO();
        liId = da.shId();
        return liId;
    }

    public void setLiId(List<Integer> liId) {
        this.liId = liId;
    }

    public List<PatientReg> getShowAllP() {
        PatientRegDAO da = new PatientRegDAO();
        showAllP = da.showAll();
        return showAllP;
    }

    public void setShowAllP(List<PatientReg> showAll) {
        this.showAllP = showAll;
    }

    public void findaPatient() {
        PatientRegDAO da = new PatientRegDAO();
        PatientReg p = da.aPatientReg(id);
        this.id = p.id;
        this.password = p.password;
        this.name = p.name;
        this.address = p.address;
        this.mobileNo = p.mobileNo;
        this.email = p.email;
        this.gender = p.gender;
        this.age = p.age;
        this.bookDate = p.bookDate;
        this.treatment = p.treatment;
        this.treatmentFor = p.treatmentFor;
        this.feedback = p.feedback;
    }

}
